buildscript {
	repositories {
		mavenCentral()
	}

	dependencies {
		classpath "com.guardsquare:proguard-gradle:7.8.1"
	}
}

import proguard.gradle.ProGuardTask

plugins {
	id 'java'
	id("xyz.jpenilla.run-paper") version "2.3.1"
	id("com.gradleup.shadow") version "9.6.1"
	id("com.diffplug.spotless") version "8.9.0"
	id("com.github.spotbugs") version "6.5.9"
	id("io.github.khstov.string-veil") version "0.2.1"
}
configurations {
	proguardLibrary {
		canBeResolved = true
		canBeConsumed = false
		extendsFrom compileOnly
	}
}
group = 'dragon.me'
version = '1.0.0'

repositories {
	mavenCentral()

	maven {
		name = "papermc-repo"
		url = "https://repo.papermc.io/repository/maven-public/"
	}

	maven {
		name = "FAWE"
		url = "https://maven.enginehub.org/repo/"
	}

	maven {
		name = "CodeMC"
		url = uri("https://repo.codemc.io/repository/maven-public/")
	}

	maven {
		url 'https://jitpack.io'
	}
	maven {
		url = 'https://repo.extendedclip.com/releases/'
	}
}

dependencies {

	implementation(platform("com.intellectualsites.bom:bom-newest:1.56"))

	proguardLibrary(platform("com.intellectualsites.bom:bom-newest:1.56"))

	compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")

	implementation("org.incendo:cloud-core:2.0.0")
	implementation("org.incendo:cloud-paper:2.0.1")
	implementation("org.incendo:cloud-annotations:2.0.0")
	implementation("org.incendo:cloud-minecraft-extras:2.0.0")

	implementation("org.spongepowered:configurate-yaml:4.2.0")

	implementation(platform("com.intellectualsites.bom:bom-newest:1.56"))

	compileOnly("com.fastasyncworldedit:FastAsyncWorldEdit-Core")

	compileOnly("com.fastasyncworldedit:FastAsyncWorldEdit-Bukkit") {
		transitive = false
	}

	implementation("com.j256.ormlite:ormlite-core:6.1")
	implementation("com.j256.ormlite:ormlite-jdbc:6.1")

	implementation("com.github.ben-manes.caffeine:caffeine:3.2.4")

	compileOnly 'me.clip:placeholderapi:2.12.3'
}

spotbugs {
	ignoreFailures = true
	effort = 'max'
	reportLevel = 'medium'
}

tasks.named('spotbugsMain') {
	reports {
		html {
			required = true
			outputLocation = file("$buildDir/reports/spotbugs.html")
		}

		xml {
			required = false
		}
	}
}

spotless {
	format 'misc', {
		target '*.gradle', '.gitattributes', '.gitignore'

		trimTrailingWhitespace()
		leadingSpacesToTabs()
		endWithNewline()
	}

	java {
		palantirJavaFormat("2.79.0")
		removeUnusedImports()
		formatAnnotations()
	}
}

def targetJavaVersion = 21

java {
	def javaVersion = JavaVersion.toVersion(targetJavaVersion)

	sourceCompatibility = javaVersion
	targetCompatibility = javaVersion

	if (JavaVersion.current() < javaVersion) {
		toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'

	if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
		options.release.set(targetJavaVersion)
	}
}

processResources {
	def props = [version: version]

	inputs.properties props
	filteringCharset 'UTF-8'

	filesMatching('plugin.yml') {
		expand props
	}
}

tasks.shadowJar {
	archiveClassifier.set("")
}

tasks {
	runServer {
		minecraftVersion("1.21.11")
	}

	build {
		dependsOn(spotlessApply)
		dependsOn("proguard")
	}
}

def testDir = file("C:\\Workspace\\Szerverek\\Dragon's Test server")
stringVeil {
	enabled = true

	failOnSecretLikeLiterals = false
	includePackages = ["dragon.me.solar"]
}

tasks.register("copyToTestServer") {
	dependsOn(tasks.named("proguard"))

	description = "Copies the obfuscated JAR to the test server's plugins folder."

	doLast {
		def pluginsDir = new File(testDir, "plugins")

		if (!pluginsDir.exists()) {
			throw new GradleException(
				"Plugins directory does not exist: ${pluginsDir}"
			)
		}

		copy {
			from file("$buildDir/libs/${project.name}-${version}-obf.jar")
			into pluginsDir
		}

		println "Copied ${project.name}-${version}-obf.jar to ${pluginsDir}"
	}
}

tasks.register("runTestServer", Exec) {
	dependsOn("copyToTestServer")

	workingDir(testDir)
	commandLine("cmd", "/c", "run.bat")
}

/*
 * Shadow JAR
 *
 * Creates:
 * build/libs/Solar-1.0.0.jar
 */
tasks.shadowJar {
	dependsOn(tasks.named("stringVeilObfuscateJvm"))
	archiveClassifier.set("")
}

/*
 * ProGuard
 *
 * Input:
 * build/libs/Solar-1.0.0.jar
 *
 * Output:
 * build/libs/Solar-1.0.0-obf.jar
 */
def zuluJavaHome = file("C:/Program Files/Zulu/zulu-25")

tasks.register("proguard", ProGuardTask) {
	dependsOn(tasks.named("shadowJar"))

	configuration(file("proguard.pro"))

	injars(tasks.named("shadowJar").flatMap { it.archiveFile })

	outjars(file("$buildDir/libs/${project.name}-${version}-obf.jar"))

	// JDK 25 modules
	fileTree("${zuluJavaHome}/jmods") {
		include("*.jmod")
	}.files.each { jmod ->
		libraryjars(
			jmod,
			jarfilter: "!**.jar",
			filter: "!module-info.class"
		)
	}

	configurations.proguardLibrary.resolve().each { dependency ->
		libraryjars(dependency)
	}
}
